print("M   M     A     RRRR    IIIII     A  ")
print("MM MM    A A    R   R     I      A A ")
print("MM MM   A   A   R   R     I     A   A")
print("M M M   AAAAA   RRRR      I     AAAAA")
print("M   M   A   A   R R       I     A   A")
print("M   M   A   A   R  R      I     A   A")
print("M   M   A   A   R   R   IIIII   A   A")
